id: P006741
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:24.789585
source_metadata:
  id: bdr:W21878
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད་ཆོས་དབང་གྲགས་པའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    bd0d9b49e46645e498fbd69994f9b4a5:
      image_group_id: I4755
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
