id: I5919D4C5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:38:16+00:00'
last_modified: '2022-06-08T06:31:50.088321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21878
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད་ཆོས་དབང་གྲགས་པའི་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1E48:
      image_group_id: I4755
      title: ''
      total_pages: 228
      order: 1
      base_file: 1E48.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
